### ISSUE TITLE
Add multiple postgis DB and tests

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-lizsync-plugin#10]
```yml
test 1:
    - description: "Ce test fait truc"
    - query:
        - database: clone_a
        - sql: UPDATE machin
    - query:
        - database: central
        - sql: UPDATE machin
    - synchro:
        - from: clone_a
        
```
